### ISSUE TITLE
\node_modules\node-rfc\src\Client.h(24): fatal error C1083: Cannot open include file: 'uv.h'

### ISSUE THREAD

**Issue by clausreinke** [SAP/node-rfc#110]
I'm having no luck building `node-rfc@1.0.3` on Windows:

- `nwrfc750P_2-70002755\nwrfcsdk\lib` exists and is in `%PATH%`
- `SAPNWRFC_HOME` is set to `nwrfc750P_5-70002755\nwrfcsdk`
- `cmake-3.15.5-win64-x64\bin` is in `%PATH%`

The buld fails trying to find `uv.h`.

**Comment by clausreinke** [comment]
I have no experience with cmake, but if I read `node-rfc/CMakeLists.txt` correctly, it expects the include files in `AppData\Roaming\npm` (`npm -g root`)

Windows node installers do not come with include files, but they seem to be available as separate version-specific tarballs (eg https://nodejs.org/dist/latest-v8.x/node-v8.16.2-headers.tar.gz). The build script would need to download and unpack the matching version someplace where it can find it.

I tried unpacking the headers for my node version where cmake seems to be looking, which gets me beyond the "missing uv.h" issue, but now I'm seeing lots of identifier errors in `winnt.h` and `winbase.h`. 

So I'm still stuck here.

I also tried going back to the last version that worked for us (rc10), but I'm getting compile errors there, too, starting with
```
..\src\rfcio.cc(189): error C2666: 'Napi::TypedArrayOf<uint8_t>::operator []': 3 overloads have similar conversions [C:\project\node_modules\node-rfc\build\sapnwrfc.vcxproj]
```
the only change I can recall since our last successful build is updating to the newest version of node 8.

Any suggestions?

**Comment by clausreinke** [comment]
it was weird that even the previously known good version didn't build anymore, so I uninstalled all node/npm and removed all corresponding folders, then reinstalled (via nvm) node 12.13.1 and 8.16.2 from scratch.  I can now install node-rfc@1.0.3 in both without issue, so there was likely something wrong with my installation. Very confusing.

**Comment by bsrdjan** [comment]
Re-open because this is actually a bug.

Build from source requires NodeJS header files and these are not always installed on a target build system. Standard nodejs installers usually install only `node` and `npm` executables. The node version manager might install headers files but not necessarily. Headers are for example included in all platforms' archives, except Windows: https://nodejs.org/download/release/latest/ 

Current CMake build script does not handle the case when headers are missing, need to be fixed.
