### ISSUE TITLE
support install on windows without manual editing

### ISSUE THREAD

**Issue by clausreinke** [SAP/node-rfc#17]
I ran into 2 small issues when trying to install/use this on windows (via git bash), forcing me to edit the sources before `npm install`. With a couple of changes, manual editing can be avoided:
1.  binding.gyp:
   
   `"msvs_nwrfcsdk_path": "$(SAPNWRFC_HOME)",`
   
   this works on windows, at least under git bash, and matches what you do on linux
2. index.js:
   before the `require(plattformPath)`
   
   `plattformPath += '-' + require('process').version;`
   
   to match the versioned "target_name" in binding.gyp

**Comment by eshikafe** [comment]
I had the same issue:

C:\Users\eausaig>git clone https://github.com/SAP/node-rfc.git
Cloning into 'node-rfc'...
remote: Counting objects: 301, done.
remote: Total 301 (delta 0), reused 0 (delta 0), pack-reused 301R
Receiving objects: 100% (301/301), 13.12 MiB | 689.00 KiB/s, done.

Resolving deltas: 100% (129/129), done.

C:\Users\eausaig>cd node-rfc

C:\Users\eausaig\node-rfc>npm install
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> node-rfc@0.1.5 install C:\Users\eausaig\node-rfc
> node-gyp rebuild


C:\Users\eausaig\node-rfc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gy
p-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: Undefined variable msvs_nwrfcsdk_path in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configur
e.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\eausaig\node-rfc
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! node-rfc@0.1.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rfc@0.1.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-rfc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-rfc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-rfc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\eausaig\node-rfc\npm-debug.log

C:\Users\eausaig\node-rfc>

**Comment by bsrdjan** [comment]
fixed by v0.1.6
