### ISSUE TITLE
Module not found 

### ISSUE THREAD

**Issue by BenGeva** [SAP/node-rfc#20]
Hi!

Thank you for this package.
We are using the v0.1.6.
First, we tried to require the 'node-rfc-master'. 
We noticed, after early testing, that the index.js file (inside the node-rfc-master folder) was referring to a non existing path and received a 'Could not load module' in the console(err.code==='MODULE_NOT_FOUND').
So we changed it to './lib/windows_x64/rfc-6.9.1', as we are using a 64x windows machine, 
but we got a new error object where err.code === undefined and the a console.log of 'Error loading module - (may SAP RFC library in path not set?) Error: The specified module could not be found, followed by the path to the existing 'rfc-6.9.1.node' file.
We also tried to require 'rfc-6.9.1.node' directly and got the same error object.

We did both extend PATH and set SAPNWRFC_HOME variables to the lib folder of nwrfcsdk.
node -v 
v6.9.1.

Thank you in advance,
Ben

**Comment by io-pa** [comment]
Hello,

node-rfc v0.1.7 fixed a lot of deployment issues.
Is there any particular reason for using v0.1.6?
If you are using node v6.9.1 and windows x64 it is possible (for node-rfc v0.1.7) to use the precompiled binary via `npm install node-rfc` .
Otherwise you could upload your node-rfc installation log for further inspection.

**Comment by io-pa** [comment]
Update: It is now actually possible to use `npm install node-rfc` (to install the latest node-rfc version).

**Comment by BenGeva** [comment]
Fixed with v0.1.7
Thanks!
