### ISSUE TITLE
Question about nwrfcsdk 7.01 support

### ISSUE THREAD

**Issue by jarag93** [SAP/node-rfc#214]
Hello, the documentation specifies that is is suggested to use sapnwrfc version 7.50, but I wanted to know if the module is also compatible older versions of netweaver, e.g. version 7.01?

**Comment by bsrdjan** [comment]
Using the latest `node-rfc` and the latest, 7.50 version of SAP NWRFC SDK is required only on client (NodeJS) side because older SDK versions are not supported.

The SDK is backwards compatible and works with all NetWeaver versions down to 4.6C, thus also with 7.01

https://support.sap.com/en/product/connectors/nwrfcsdk.html

**Comment by ilirasllani** [comment]
Yes, my question was more regarding the client, so to have the NodeJS client functional, it would be necessary to upgrade the SAP NWRFC SDK to 7.50, as only then the `sapnwrfc.node` be successfully loaded?

**Comment by bsrdjan** [comment]
Hi Ilir,

that is correct and here the background.

SAP NWRFC SDK remains fully backward compatible but new releases bring new functionality and new SDK API methods. The current SDK 7.50 PL8 for example provides WebSocket RFC connectivity and SDK API Method `RfcLoadCryptoLibrary`. The new node-rfc version "follows" and expects to find that SDK method when loaded. That is why newer node-rfc (sapnwrfc.node) loading fails with older SDK version. Node-rfc could check SDK version and skip missing APIs but that would result in more complexity and testing efforts. It might also bring users in trouble because only the current SDK version is supported and should be used. It might happen that node-rfc works but older SDK has a bug which is already fixed in newer SDK. Therefore always the latest SDK should be used on client and ABAP backend practically does not matter. Older SDK should work with one of older node-rfc versions but why would you need the older SDK? 

Kind regards,
srdjan

**Comment by jarag93** [comment]
thanks for the information
