### ISSUE TITLE
env variable SAPNWRFC_HOME read wrong on Windows 2016

### ISSUE THREAD

**Issue by uwehommel** [SAP/node-rfc#237]
**Describe the bug**
there is always an additional / when the environment variable is red in Node-Red
configure as C:/nwrfcsdk

only in Node Red it is reported as C://nwrfcsdk and therefore the sdk cannot be loaded

**To Reproduce**
Describe how the `node-rfc` is installed, like locally or globally and using `npm install` or build from source.

Describe steps to reproduce the behavior, including the test script.

**Screenshots**

**Environment**
 - The output of `node -p "require('node-rfc').environment"`

**Additional context**

**Comment by bsrdjan** [comment]
Sorry for the pending response here. The '\\' is standard output representation on Windows (esc character + folder separator).

The reason why node-rfc is not loading is because the node-rfc and SAP NWRFC SDK are not supported on Node-RED platform. See: #161 and #148

The node-rfc README section about Node-RED will be updated, pointing to these feature requests.
