### ISSUE TITLE
Receiving IDOCs with this library

### ISSUE THREAD

**Issue by apexmavi** [SAP/node-rfc#259]
Can I use this library to receive IDOCS from SAP server? I have gotten the server script up and running but I get error message about transaction handler not being installed. Is this perhaps something not implemented yet on node-rfc ?

**Comment by panditha** [comment]
Hi @bsrdjan ,

We are trying to achieve the same thing to receive idocs from SAP and our receiving platform is based on nodejs and not java. From our understanding (correct us if we are wrong) the underlying technical framework is same RFC functions except that there are predefined function names for exchanging idocs. For example, IDOC_INBOUND_ASYNCHRONOUS is the function for inbound into SAP and we are successfully able to send idoc to SAP by calling this function. In similar way we are expecting that if nodejs server exposes the same function we should be able to receive the idoc.

We are trying to receive idocs now, we are able to start the server, expose the IDOC_INBOUND_ASYNCHRONOUS function and also able to see the connection established on RFC gateway. However, when we trigger an idoc in SAP it says successfully submitted but on nodejs side the server simply exits without any error message. We do feel that SAP did contact nodejs server and then crashed because if we don't trigger idoc in SAP then the node server is not crashing.

Can you please guide us here on how to further debug this.
