### ISSUE TITLE
Is it possible to run node-rfc in fiori app ?

### ISSUE THREAD

**Issue by siasty** [SAP/node-rfc#262]
As the topic. 
Is it possible to run node-rfc in fiori controller? i install module in node_modules but i don't know how to attach it

**Comment by bsrdjan** [comment]
Which controller exactly do you mean? Where is it running, in browser ?

**Comment by siasty** [comment]
Yes i tried to use in browser
![image](https://user-images.githubusercontent.com/39690589/184882432-5f995c49-d537-4d5c-8c47-e1e8bb5f47d4.png)

**Comment by bsrdjan** [comment]
The `node-rfc` is not supported in web browsers, only on servers, where the nodejs is running. The reason is native node-rfc dependency SAP NWRFC SDK (pre-compiled SAP C++ binaries implementing RFC protocol), which is running on server platforms only: https://launchpad.support.sap.com/#/notes/2573790

**Comment by bsrdjan** [comment]
Why not run `node-rfc` on server and consume from Fiori controller?

**Comment by siasty** [comment]
thx. I understand. I wanted to try if there is such a possibility
