### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by EdisonNetcon** [SAP/node-rfc#277]
Hi team, I got the following error randomly in my SAP call from the node application.

"\nLOCATION    CPIC (TCP/IP) on local host with Unicode\nERROR       connection to partner '**IP address**:3301' broken\nTIME        Tue Jan 17 15:01:41 2023\nRELEASE     753\nCOMPONENT   NI (network interface)\nVERSION     40\nRC          -6\nMODULE      D:/depot/bas/753_REL/src/base/ni/nixxi.cpp\nLINE        5434\nDETAIL      NiIRead: P=**IP address**:3301; L=**IP address**::55451\nSYSTEM CALL recv\nERRNO       10054\nERRNO TEXT  WSAECONNRESET: Connection reset by peer\nCOUNTER     9"}

I try to reproduce it on my local machine, but I could not do it. As well as I need to know what is COUNTER 9.
What is the reason for this error? How can I fix this? 

Does anyone help me?

**Comment by bsrdjan** [comment]
The counter is for internal diagnostics only. Is the error reproducible, like occurring for every call or randomly? Occurs are logon or after logon, when trying to make RFC call?

In either case, we need a C-PIC trace, to analyse the root cause. Ti capture RFC trace, set the global trace level to "3", in `sapnwrfc.ini` file, as in below example. Then reproduce the error and send the trace.

If ABAP backend belongs to SAP customer, create an customer incident for `BC-MID-RFC-SDK` component, attach the trace to incident and send me the link.

**sapnwrfc.ini**

```ini
DEFAULT
RFC_TRACE=3 # 'global' trace level

DEST=QM7
USER=demo
PASSWD=welcome
ASHOST=ldciqm7
SYSNR=00
CLIENT=005
LANG=EN
# RFC_TRACE=2 # 'local' trace level 
```
