### ISSUE TITLE
node-rfc internal error: wrapString (Thai Language)

### ISSUE THREAD

**Issue by potcharapon** [SAP/node-rfc#57]
Trying to display the customer's name on a webpage by calling **BAPI_CUSTOMER_GETDETAIL2**. The message saved on the record is `ทดสอบสร้างลูกค้าจากภายนอกครั้งที่ 31 วันที่ 20180821 เวลา 15:38` which then concatenated into parts, 35 char each. i.e.

`name_1: 'ทดสอบสร้างลูกค้าจากภายนอกครั้งที่ 3'`
`name_2: '1 วันที่ 20180821 เวลา 15:38'`

After the record is saved.Viewing the data via SAP GUI calling **BAPI_CUSTOMER_CREATEFROMDATA1** to check. The result is correctly displayed:

`CUSTOMERADDRESS.NAME: 'ทดสอบสร้างลูกค้าจากภายนอกครั้งที่ 3'`
`CUSTOMERADDRESS.NAME_2: '1 วันที่ 20180821 เวลา 15:38'`

Then we went back and check the record using the function **BAPI_CUSTOMER_GETDETAIL2** the error occurs:

`CUSTOMERADDRESS.NAME: 'node-rfc internal error: wrapString'`
`CUSTOMERADDRESS.NAME_2: '1 วันที่ 20180821 เวลา 15:38'`
### Example
From SAP GUI
```
Function BAPI_CUSTOMER_GETDETAIL2
Export Parameter:  CUSTOMERADDRESS
Field: NAME Value: ‘ทดสอบสร้างลูกค้าจากภายนอกครั้งที่ 3’
Field: NAME_2 Value: ‘1 วันที่ 20180821 เวลา 15:38’
```
From node-rfc
```
Function BAPI_CUSTOMER_GETDETAIL2
Response : {
    CUSTOMERADDRESS: {
        …
        NAME: 'node-rfc internal error: wrapString',
        NAME_2: '1 วันที่ 20180821 เวลา 15:38',
        …
    }, {
        …
    }
}
```
### File
sapRFC.js
```
const config = require('./config');
const rfc = require('node-rfc');
const connParams = {
     user: config.sap.user,
     passwd: config.sap.passwd,
     ashost: config.sap.ashost,
     sysnr: config.sap.sysnr,
     client: config.sap.client,
     lang: 2
};
const clientSAP = new rfc.Client(connParams, true);
module.exports = clientSAP;

```
model_sap.js
```
const Promise = require('bluebird');
const _ = require('lodash');
const sapRFC = require('../config/sapRFC');
const modelSAP = {
    sapConnect: function () {
        return new Promise(function (resolve, reject) {
            if (sapRFC) {
                sapRFC.close(function (err) { console.error(err) });
                if (!sapRFC.ping()) {
                    return sapRFC.connect(function (err) {
                        if (err) return reject(err);
                        return resolve(true);
                    });
                } else {
                    return resolve(true);
                }
            } else {
                throw Error('Error Connect SAP!');
            }
        });
    },
    sapCustomerGet: function (CUSTOMERNO, USER) {
        return new Promise(function (resolve, reject) {
            if (!CUSTOMERNO) return reject('CUSTOMERNO Invalid');
            return modelSAP.sapConnect().then(function (_stauts) {
                var response = {};
                return new Promise(function (resolve2, reject2) {
                    var objSAP = {
                        CUSTOMERNO: (parseInt(CUSTOMERNO)).pad(10),
                        COMPANYCODE: '1000'
                    };
                    if (USER.hasOwnProperty('sale_company')) {
                        if (USER.sale_company) objSAP.COMPANYCODE = USER.sale_company;
                    }
                    return sapRFC.invoke('BAPI_CUSTOMER_GETDETAIL2', objSAP, function (err, res) {
                        if (err) return reject2(err)
                        response  = res;
                        return modelLogSAP.saveByData(USER.id, 'sapCustomerGet', 'BAPI_CUSTOMER_GETDETAIL2', objSAP, res, res.RETURN).then(function () {s
                            return resolve2(res);
                        });
                    });
                }).then(function (_status) {
                    sapRFC.close(function (err) { console.error(err) });
                    return resolve(response);
                });
            }).catch(function (error) {
                console.error('### Error model modelSAP.sapCustomerGet', error);
                return reject(error)
            });
        });
    }
}
module.exports = modelSAP;
```

**Comment by bsrdjan** [comment]
Could you please post the nodejs version, node-rfc version (`sapRFC.getVerson()` output) and the platform (Windows/Linux) ?

If not using already, please feel free to try `node-rfc@next` and check if the issue still occurs? This new release offers also (bluebird based) Promise API.

**Comment by thaicyber** [comment]
node-rfc@next release (1.0.0-rc2) 
Test wrapString support thai language

**Comment by thaicyber** [comment]
**function  error.**

client.close() 
![image](https://user-images.githubusercontent.com/16860156/44441409-8fecd180-a5f6-11e8-82ad-8eea3e8a61db.png)

client.ping()
![image](https://user-images.githubusercontent.com/16860156/44441452-b9a5f880-a5f6-11e8-8a53-3f21f220a365.png)

**Comment by bsrdjan** [comment]
`ping()` and `close()` are now non-blocking and require a callback function as argument. Thanks for finding this, will add to [CHANGES](https://github.com/SAP/node-rfc/blob/napi/CHANGES).

Using callback API, you could provide a dummy like `ping( () => {} )`, like in [unit test examples](https://github.com/SAP/node-rfc/blob/napi/test/connection.spec.js#L127).

Promise API requires no arguments, as in this [unit test](https://github.com/SAP/node-rfc/blob/napi/test/connection.promise.spec.js#L97).

You could also consider [async/await](https://github.com/SAP/node-rfc/blob/napi/examples/README.md)

As a side note,  there are two methods to check if the connection is still alive.

`isAlive` getter ([unit test](https://github.com/SAP/node-rfc/blob/napi/test/connection.spec.js#L118)) indicates if SAP NW RFC library still "considers" the connection open. It is not absolutely reliable because the firewall may silently have closed the connection, without notifying endpoints and SAP NW RFC lib still "considers" the connection open.

`ping()` is the only absolutely reliable method but also the most expensive (slowest) because of the full request/response cycle it has to perform, to check if the connection is really open.

In many cases, `isAlive` is enough and much faster.

**Comment by potcharapon** [comment]
@bsrdjan. Thank you for solve this issue. I try it and woking very well.

**Comment by potcharapon** [comment]
-
