### ISSUE TITLE
npm install node-rfc@next fails in ubuntu with ENOTEMPTY: directory not empty

### ISSUE THREAD

**Issue by aaronortiz** [SAP/node-rfc#60]
![image](https://user-images.githubusercontent.com/8881155/47233658-090b6980-d399-11e8-8f32-121b32ff4fd5.png)

Log file here:
https://drive.google.com/open?id=1f_aTLGE3AM0MlT_6isNkuQ8iLRCSvEA8

I tried to install node-rfc in a fresh ubuntu virtual machine with the command:
`npm install node-rfc@next`
but got the error above. Can you help me fix this?

thanks, 

-AO

**Comment by bsrdjan** [comment]
Please upgrade the npm, like `npm i npm` for example and retry.

**Comment by aaronortiz** [comment]
Hi bsrdjan,

   I did as you asked (sudo npm i npm, and then sudo npm install node-rfc@next) and got an almost identical error:
![image](https://user-images.githubusercontent.com/8881155/47312781-e41a2f00-d602-11e8-8ae3-01af2f03f50a.png)

New debug log [here](https://drive.google.com/open?id=1iHJayJOmdvlNe92MhrFSkEPrS4FO56gw)

**Comment by bsrdjan** [comment]
Hi @aaronortiz,

both the screenshot and the log show the npm v3.5.2, which is no longer supported. The ENOTEMPTY looks like [known npm issue](https://github.com/SAP/node-rfc/issues/56#issuecomment-405240589) and the upgrade fixed the same problem I had.

You may check the `npm -v` before the installation, also try using the node version manager like [nvm](https://github.com/creationix/nvm), so no admin rights needed to upgrade. Or use [yarn](https://yarnpkg.com/en/).

**Comment by bsrdjan** [comment]
it should be `npm -g install npm`, to update the global npm on ubuntu or in current nvm node version

**Comment by aaronortiz** [comment]
Thanks Srdjan, 

After many many failures, I did a very throrough chown of all the contents of node_modules. I also did a general update and upgrade of all my ubuntu apt packages. Finally I installed node-pre-gyp separately through npm. (https://www.npmjs.com/package/node-pre-gyp) 

finally, the command that suceeded in installing node-rfc was:
`npm install node-rfc`

Notice the lack of sudo and @next.

thanks,

Aaron Ortiz

**Comment by bsrdjan** [comment]
Hi Aaron,

as the fix could be helpful for other Ubuntu users, could you please share the Ubuntu version and  nodejs version? Also if the node was the part of VM image or installed (how?) after the installation?

Thanks and regards,
Srdjan

**Comment by aaronortiz** [comment]
I did install nvm, but didn't get around to trying it.

`node -v` returns:
`v8.10.0`

![image](https://user-images.githubusercontent.com/8881155/47867517-56d79700-ddc7-11e8-841a-dbb6af8d60e6.png)
My version of ubuntu is 10.04.1 LTS

**Comment by bsrdjan** [comment]
Just few tips, for users facing ENOTEMPTY issue during node-rfc installation.

The error is usually caused by the older version of npm, shipped with the node version you are using. The solution is to upgrade the npm, which should be done anyway, considering [only the latest npm version is supported](https://npm.community/t/enotempty-directory-not-empty-rename-on-nodejs-6-only/513/4) and using the latest stable version is recommended in general.

Using node version manager like [nvm](https://github.com/creationix/nvm) simplifies the installation and handling of multiple node versions on your Linux, macOS or Windows systems. Upgrading npm after node release installation is a good practice, preventing ENOTEMPTY and other issues.

The issue is reproducible with 6.14.4 (and earlier), [coming with npm 3](https://nodejs.org/en/download/releases/):
![screenshot 2018-11-02 at 12 04 54](https://user-images.githubusercontent.com/1697847/47912058-9968a480-de97-11e8-9dc2-58c3e278e890.png)

To upgrade, just run:

```shell
npm -g install npm
npm -v 
6.4.1
```
