### ISSUE TITLE
How would you loop a bapi?

### ISSUE THREAD

**Issue by PaulWieland** [SAP/node-rfc#97]
I have an array of userID's and email addresses. I want to loop through the array and call `BAPI_USER_CHANGE` to update the user's email.

Just putting `client.call` in a `forEach` fails with the following error: 
`called function STSEND in state state=BUFFER_DATA2`.

After some searching, I found [this issue](https://github.com/SAP/node-rfc/issues/16). 

Because `client.call` is asynchronous, and because you can't submit parallel requests with the same client, we have this problem when trying to do an RFC in a loop... (EDIT: Begs the question if the library should offer a solution for this, since we have an async client but a server that doesn't support async calls?)

So what is the "right" (cleanest) way?

**Comment by bsrdjan** [comment]
Considering one node-rfc client instance can handle one RFC call at the time, two solutions are possible. Opening multiple clients/connections, calling `BAPI_USER_CHANGE` in parallel, or using single client/connection instance and calling `BAPI_USER_CHANGE` sequentially, like ABAP LOOP would do. The only wisdom in sequential approach is how to trigger the next call after the previous one is completed. 

Examples for that (and for parallelisation) you may find in [concurrency unit tests](https://github.com/SAP/node-rfc/tree/napi/test/concurrency), like [sequential by async/await](https://github.com/SAP/node-rfc/blob/napi/test/concurrency/await.spec.js#L43) or [sequential by callback](https://github.com/SAP/node-rfc/blob/napi/test/concurrency/promise.spec.js#L77).

Generic solution in a library would support either only one of these patterns, which is not good, or all patterns, which would complicate the usage and testing because of possible combinations. I would rather offer convention based solution, like these unit test patterns showing how to solve the problem and better document it, including an example in README. Do you think it would help other users?

**Comment by PaulWieland** [comment]
> Opening multiple clients/connections, calling BAPI_USER_CHANGE in parallel

That was my first thought, but I was concerned about flooding the server with thousands of connections. I didn't try it yet for fear of causing a performance issue on the server side, or hitting a connection limit.

> or using single client/connection instance and calling BAPI_USER_CHANGE sequentially, like ABAP LOOP would do.

This is essentially what I am trying to figure out how to do. Thank you for sharing the unit test patterns, I will follow one of those.

I do think it would be very helpful to have examples in the README. I expect this is a very common problem that users encounter. In my mind, the best application for `node-rfc` is automation of repetitive tasks - which almost always means looping.

**Comment by PaulWieland** [comment]
Perhaps this is a good application for [cwait](https://github.com/charto/cwait)

**Comment by bsrdjan** [comment]
Thanks for the nice example. Flooding the server with too many connections should actually not be possible in a standard ABAP system, with RFC configuration restricting max number of parallel connections, timeout etc. but better not pushing the system to its limits if not really needed.

The parallelisation can help faster upload or download large amounts or data and sequential calls are the only possibility when the next call depends on the result of the previous one, or must start after previous one completed. 

Both patterns are needed commonly used, will add some examples in README.

**Comment by PaulWieland** [comment]
> The parallelisation can help faster upload or download

This is the nice thing about `cwait`. You can change the second parameter for the constructor to tell it how many to process in parallel.

`var queue = new cwait.TaskQueue(Promise, 4);` would cause 4 items to process at a time.
